---
version: "3"
services:
 devopsdb:
   
   image: avinashvuppu/mynewapp:dbimage
   ports:
     - "3306:3306"

 application:
   image: avinashvuppu/mynewapp:appimage
   
   ports:
     - "1111:8080"
   depends_on:
     - "devopsdb"
